- name: Configure router
  hosts: cisco_switches
  gather_facts: no
  tasks:
  - name: run show commands
    ansible.netcommon.telnet:
      user: admin
      password: cisco
      login_prompt: "Username: "
      password_prompt: "Password: "
      prompts:
        - '[>|#]'
      commands:
        - terminal length 0
        #- show version
        #- show vlan
    register: cmd
  - name: output
    debug: msg="{{cmd.output}}"